import { useEffect, useState } from "react";
import { useLocation, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Button } from "../components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../components/ui/card";
import { Progress } from "../components/ui/progress";
import { Badge } from "../components/ui/badge";
import Navigation from "../components/Navigation";
import {
  detectFracture,
  getFractureInfo,
  type DetectionResult,
} from "../utils/fratureDetection";
import {
  Download,
  AlertTriangle,
  CheckCircle,
  Info,
  ArrowLeft,
} from "lucide-react";
import jsPDF from "jspdf";

const ResultsPage = () => {
  const location = useLocation();
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);

  useEffect(() => {
    const { fileName } = location.state || {};
    if (fileName) {
      const detectionResult = detectFracture(fileName);
      setResult(detectionResult);
    }
  }, [location.state]);

  const generatePDFReport = async () => {
    if (!result || !location.state?.fileName) return;

    setIsGeneratingReport(true);

    try {
      const pdf = new jsPDF();
      const { fileName, uploadTime } = location.state;

      // Header
      pdf.setFontSize(20);
      pdf.text("Bone Fracture Detection Report", 20, 30);

      pdf.setFontSize(12);
      pdf.text(`Generated by BoneDetect AI`, 20, 45);
      pdf.text(`Date: ${new Date(uploadTime).toLocaleDateString()}`, 20, 55);
      pdf.text(`Image: ${fileName}`, 20, 65);

      // Results
      pdf.setFontSize(16);
      pdf.text("Analysis Results", 20, 85);

      pdf.setFontSize(12);
      if (result.isNormal) {
        pdf.text("Status: Normal - No fracture detected", 20, 100);
        pdf.text(`Confidence: ${result.confidence}%`, 20, 110);
      } else if (result.isSuspect) {
        pdf.text("Status: Inconclusive - Further evaluation needed", 20, 100);
        pdf.text(`Confidence: ${result.confidence}%`, 20, 110);
      } else if (result.fractureType) {
        const fractureInfo = getFractureInfo(result.fractureType);
        pdf.text(
          `Status: Fracture Detected - ${fractureInfo?.name || "Unknown"}`,
          20,
          100
        );
        pdf.text(`Confidence: ${result.confidence}%`, 20, 110);
      }

      // AI Recommendation
      pdf.setFontSize(16);
      pdf.text("AI Recommendation", 20, 130);

      pdf.setFontSize(10);
      const splitRecommendation = pdf.splitTextToSize(
        result.aiRecommendation,
        170
      );
      pdf.text(splitRecommendation, 20, 145);

      // Fracture Details (if applicable)
      if (result.fractureType && !result.isNormal) {
        const fractureInfo = getFractureInfo(result.fractureType);
        if (fractureInfo) {
          pdf.setFontSize(16);
          pdf.text("Fracture Information", 20, 180);

          pdf.setFontSize(10);
          pdf.text(`Description: ${fractureInfo.description}`, 20, 195);
          pdf.text(`Recovery Time: ${fractureInfo.recoveryTime}`, 20, 205);
          pdf.text(`Treatment: ${fractureInfo.treatment}`, 20, 215);
        }
      }

      // Disclaimer
      pdf.setFontSize(8);
      pdf.text(
        "Disclaimer: This AI analysis is for educational purposes only and should not replace professional medical diagnosis.",
        20,
        270
      );

      pdf.save(`fracture-report-${fileName}-${Date.now()}.pdf`);
    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setIsGeneratingReport(false);
    }
  };

  if (!result || !location.state?.fileName) {
    return (
      <div className="min-h-screen bg-linear-to-br from-slate-900 via-slate-800 to-slate-900">
        <Navigation />
        <div className="pt-24 flex items-center justify-center">
          <Card className="bg-slate-800/50 border-slate-600 max-w-md">
            <CardContent className="p-8 text-center">
              <AlertTriangle className="w-16 h-16 text-yellow-500 mx-auto mb-4" />
              <h2 className="text-xl font-bold text-white mb-2">
                No Analysis Data
              </h2>
              <p className="text-slate-300 mb-4">
                Please upload an X-ray image first.
              </p>
              <Link to="/upload">
                <Button className="bg-blue-600 hover:bg-blue-700">
                  Go to Upload
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  const getStatusColor = () => {
    if (result.isNormal) return "bg-green-600";
    if (result.isSuspect) return "bg-yellow-600";
    return "bg-red-600";
  };

  const getStatusIcon = () => {
    if (result.isNormal) return CheckCircle;
    if (result.isSuspect) return Info;
    return AlertTriangle;
  };

  const StatusIcon = getStatusIcon();
  const fractureInfo = result.fractureType
    ? getFractureInfo(result.fractureType)
    : null;

  return (
    <div className="min-h-screen bg-linear-to-br from-slate-900 via-slate-800 to-slate-900">
      <Navigation />

      <div className="pt-24 pb-16 px-6">
        <div className="container mx-auto max-w-4xl">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center mb-8"
          >
            <h1 className="text-4xl lg:text-5xl font-bold text-white mb-4">
              Analysis Results
            </h1>
            <p className="text-xl text-slate-300">
              AI-powered fracture detection completed for:{" "}
              {location.state.fileName}
            </p>
          </motion.div>

          {/* Main Results Card */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <Card className="bg-slate-800/50 border-slate-600 mb-8">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <StatusIcon className={`w-8 h-8 text-white`} />
                    <div>
                      <CardTitle className="text-white text-2xl">
                        {result.isNormal
                          ? "Normal"
                          : result.isSuspect
                          ? "Inconclusive"
                          : "Fracture Detected"}
                      </CardTitle>
                      <CardDescription className="text-slate-300">
                        {fractureInfo?.name || "Analysis completed"}
                      </CardDescription>
                    </div>
                  </div>
                  <Badge
                    className={`${getStatusColor()} text-white px-4 py-2 text-lg`}
                  >
                    {result.confidence}% Confidence
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-6">
                  {/* Confidence Meter */}
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="text-slate-300">Confidence Level</span>
                      <span className="text-white font-medium">
                        {result.confidence}%
                      </span>
                    </div>
                    <Progress value={result.confidence} className="h-3" />
                  </div>

                  {/* AI Recommendation */}
                  <div className="bg-slate-700/50 rounded-lg p-6">
                    <h3 className="text-white font-semibold mb-3 flex items-center">
                      <Info className="w-5 h-5 mr-2 text-blue-500" />
                      AI Recommendation
                    </h3>
                    <p className="text-slate-300 leading-relaxed">
                      {result.aiRecommendation}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Fracture Details (if fracture detected) */}
          {fractureInfo && !result.isNormal && (
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
            >
              <Card className="bg-slate-800/50 border-slate-600 mb-8">
                <CardHeader>
                  <CardTitle className="text-white">
                    Fracture Information
                  </CardTitle>
                  <CardDescription className="text-slate-300">
                    Detailed information about {fractureInfo.name}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid md:grid-cols-2 gap-6">
                    <div>
                      <h4 className="text-white font-semibold mb-2">
                        Description
                      </h4>
                      <p className="text-slate-300 text-sm mb-4">
                        {fractureInfo.description}
                      </p>

                      <h4 className="text-white font-semibold mb-2">
                        Recovery Time
                      </h4>
                      <p className="text-slate-300 text-sm">
                        {fractureInfo.recoveryTime}
                      </p>
                    </div>

                    <div>
                      <h4 className="text-white font-semibold mb-2">
                        Common Symptoms
                      </h4>
                      <ul className="text-slate-300 text-sm space-y-1 mb-4">
                        {fractureInfo.symptoms
                          .slice(0, 4)
                          .map((symptom, index) => (
                            <li key={index}>• {symptom}</li>
                          ))}
                      </ul>

                      <h4 className="text-white font-semibold mb-2">
                        Treatment
                      </h4>
                      <p className="text-slate-300 text-sm">
                        {fractureInfo.treatment}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Actions */}
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="flex flex-col sm:flex-row gap-4 justify-center"
          >
            <Button
              onClick={generatePDFReport}
              disabled={isGeneratingReport}
              className="bg-blue-600 hover:bg-blue-700 px-8"
              size="lg"
            >
              {isGeneratingReport ? (
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
              ) : (
                <Download className="w-5 h-5 mr-2" />
              )}
              {isGeneratingReport ? "Generating..." : "Download Report"}
            </Button>

            <Link to="/upload">
              <Button
                variant="outline"
                className="border-slate-600 text-slate-300 hover:bg-slate-800 px-8"
                size="lg"
              >
                <ArrowLeft className="w-5 h-5 mr-2" />
                Analyze Another
              </Button>
            </Link>
          </motion.div>
        </div>
      </div>
    </div>
  );
};

export default ResultsPage;
