import { useRef, Suspense } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import type { GLTF } from "three-stdlib";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PolyOne Studio (https://sketchfab.com/polyone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-pack-human-skeleton-950d0a46531f492ab8715777e312a5bf
Title: Free Pack - Human Skeleton
*/

type GLTFResult = GLTF & {
  nodes: {
    SM_HumanSkeleton_01_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_02_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_03_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_04_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_05_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_06_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_07_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_08_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_09_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_10_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_11_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_12_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_13_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_14_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_15_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_16_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_17_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_18_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_19_Humam_Skeleton_M_0: THREE.Mesh;
    SM_HumanSkeleton_20_Humam_Skeleton_M_0: THREE.Mesh;
    OutLine_OutLine_M_0: THREE.Mesh;
  };
  materials: {
    Humam_Skeleton_M: THREE.MeshStandardMaterial;
    OutLine_M: THREE.MeshStandardMaterial;
  };
};

function HumanSkeleton(props: React.JSX.IntrinsicElements["group"]) {
  const groupRef = useRef<THREE.Group>(null);

  // Cast to unknown first, then to GLTFResult
  const gltf = useGLTF("/skeleton/scene.gltf");
  const { nodes, materials } = gltf as unknown as GLTFResult;

  useFrame((state) => {
    if (groupRef.current) {
      groupRef.current.rotation.y = state.clock.elapsedTime * 0.15;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group position={[0, -2.5, 0]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_01_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_02_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_03_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_04_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_05_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_06_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_07_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_08_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_09_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_10_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_11_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_12_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_13_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_14_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_15_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_16_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_17_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_18_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_19_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_HumanSkeleton_20_Humam_Skeleton_M_0.geometry}
          material={materials.Humam_Skeleton_M}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OutLine_OutLine_M_0.geometry}
          material={materials.OutLine_M}
        />
      </group>
    </group>
  );
}

// Preload the model
useGLTF.preload("/skeleton/scene.gltf");

const LoadingFallback = () => (
  <mesh>
    <boxGeometry args={[1, 1, 1]} />
    <meshStandardMaterial color="#3b82f6" />
  </mesh>
);

interface UltimateSkeletonModelProps {
  interactive?: boolean;
  autoRotate?: boolean;
}

const UltimateSkeletonModel = ({
  interactive = true,
  autoRotate = true,
}: UltimateSkeletonModelProps) => {
  return (
    <div className="w-full h-full relative">
      <Canvas
        camera={{ position: [15, 5, 15], fov: 45 }}
        gl={{
          antialias: true,
          alpha: true,
          preserveDrawingBuffer: true,
        }}
        style={{
          background: "linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)",
        }}
      >
        <Suspense fallback={<LoadingFallback />}>
          <ambientLight intensity={0.6} />
          <directionalLight
            position={[15, 20, 15]}
            intensity={1.2}
            castShadow
            shadow-mapSize-width={2048}
            shadow-mapSize-height={2048}
          />
          <pointLight position={[-10, -10, -10]} intensity={0.4} />
          <hemisphereLight args={["#ffffff", "#666666", 0.7]} />
          <HumanSkeleton />

          {interactive && (
            <OrbitControls
              enableZoom={true}
              enablePan={true}
              autoRotate={autoRotate}
              autoRotateSpeed={0.8}
              maxPolarAngle={Math.PI / 1.5}
              minPolarAngle={Math.PI / 6}
              maxDistance={25}
              minDistance={8}
            />
          )}
        </Suspense>
      </Canvas>
    </div>
  );
};

export default UltimateSkeletonModel;
